[package]
name = "le"
version = "0.1.0"
authors = ["Alexander Jackson <alexanderjackson@protonmail.com>"]
edition = "2018"

[dependencies]
colored = "1.7"

[dependencies.clap]
version = "2.32"
features = ["yaml"]
