[package]
name = "le"
version = "1.1.0"
authors = ["Alexander Jackson <alexanderjackson@protonmail.com>"]
edition = "2021"

[build-dependencies]
lalrpop = "0.19.9"

[dependencies]
colored = "2.0.0"
regex = "1.7.3"
pico-args = "0.5.0"
logos = "0.12.1"
lalrpop-util = "0.19.9"
