[package]
name = "le"
version = "1.1.0"
authors = ["Alexander Jackson <alexanderjackson@protonmail.com>"]
edition = "2018"

[build-dependencies]
lalrpop = "0.19.6"

[dependencies]
colored = "2.0.0"
regex = "1.5.4"
pico-args = "0.4.2"
logos = "0.12.0"
lalrpop-util = "0.19.6"
